### ISSUE TITLE
Is the code for task1 available?

### ISSUE THREAD

**Issue by LucasZhan** [neuralmind-ai/coliee#1]
Hi,

I am Xu Zhan from The University of Adelaide. This issue is a kind request for the code of task1. I found the link of this repo in the abstract in your paper "**Yes, BM25 is a Strong Baseline for Legal Case Retrieval**", which is the paper for task 1. However, this repo seems writing for task2. 

Is the code for task1 available? I am new to NLP and Q&A field. I found your paper is great and I want to reproduce it. However, reproducing the experiment without code is quite difficult for me. Could you please help me with the code of task 1?

Kind regards
Xu

**Comment by guilhermemr04** [comment]
We have updated the repository and now it includes the script for task 1.
